# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.cache/wt [current_project]
set_property parent.project_path /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.srcs/sources_1/new/somador_subtrator.vhd
  /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.srcs/sources_1/new/calcula.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.srcs/constrs_1/imports/PED/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/phantoo/git/hub/ped/PED_2018-1_trabalho_final/PED_2018-1_trabalho_final.srcs/constrs_1/imports/PED/Basys3_Master.xdc]


synth_design -top calcula -part xc7a35tcpg236-1


write_checkpoint -force -noxdef calcula.dcp

catch { report_utilization -file calcula_utilization_synth.rpt -pb calcula_utilization_synth.pb }
